version: "3"

services:
  backend:
    build: .
    command: bash /app/start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=articles_db
    ports:
      - "5432:5432"
